GitHub api client issue 24
actualize-portfolio/alumni_portfolio_api pull request #34
Opened 2022-01-12 20:17 UTC by yitzy32

## Proposed changes

GithubApi client (class) is a tool that will allow for easy DRY calls to the Github Api. So far this PR covers the `user` and `repositories` methods in the class.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Refactor (found a better way to write the code and accomplish the same task)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-13 00:13 UTC, gatorjuice reviewed
looking good and almost there

2022-01-13 19:41 UTC, yitzy32 commented on app/apis/github_api.rb
> +  def repository(project)
Added

2022-01-14 00:18 UTC, gatorjuice requested changes
Nice work, this is really nice and simple, but one criteria is still remaining on the story...

* https://github.com/actualize-portfolio/alumni_portfolio_api/blob/main/app/models/github_repo.rb uses this new client as well.

If possible could you address this change, and make sure the github tracker still works as normal?

2022-01-14 00:18 UTC, gatorjuice commented on app/apis/github_api.rb
> +  def repository(project)
very nice.

2022-01-17 20:36 UTC, gatorjuice approved these changes
LGTM!

2022-01-17 20:36 UTC, merged